spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: TwoFastDelivery

  datasource:
    url: jdbc:postgresql://localhost:5432/twofastdelivery
    username:
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  messages:
    basename: messages
    encoding: UTF-8
    always-use-message-format: true

server:
  port: 8080


mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: nbcamp.TwoFastDelivery.domain.product.dto
  configuration:
    map-underscore-to-camel-case: true

gemini:
  api:
    key: ${GEMINI_API_KEY}
    url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent"